const $=id=>document.getElementById(id),money=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"}),safe=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");
const labels={agendado:"Agendado",confirmado:"Confirmado",em_atendimento:"Em atendimento",concluido:"Concluído",cancelado:"Cancelado",nao_compareceu:"Não compareceu"};
const ymd=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
function defaults(a,b){let e=new Date(),s=new Date(e);s.setDate(1);$(a).value=ymd(s);$(b).value=ymd(e)}
function csv(name,rows){let text=rows.map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(";")).join("\r\n"),blob=new Blob(["\ufeff"+text],{type:"text/csv;charset=utf-8;"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}

let data=[],pros=[],serv=[],links=[];
async function load(){
 let i=$("relInicio").value,f=$("relFim").value,p=$("relProf").value,q=supabaseClient.from("agendamentos").select("*").gte("inicio",new Date(i+"T00:00:00").toISOString()).lte("inicio",new Date(f+"T23:59:59").toISOString()).order("inicio");if(p)q=q.eq("profissional_id",p);
 let [a,pr,se]=await Promise.all([q,supabaseClient.from("profissionais").select("id,nome").eq("ativo",true),supabaseClient.from("servicos").select("id,nome")]);if(a.error||pr.error||se.error)throw(a.error||pr.error||se.error);data=a.data||[];pros=pr.data||[];serv=se.data||[];
 $("relProf").innerHTML='<option value="">Todos</option>'+pros.map(x=>`<option value="${x.id}" ${x.id===p?"selected":""}>${safe(x.nome)}</option>`).join("");
 let ids=data.map(x=>x.id);links=[];if(ids.length){let r=await supabaseClient.from("agendamento_servicos").select("agendamento_id,servico_id").in("agendamento_id",ids);if(r.error)throw r.error;links=r.data||[]}
 $("relTotal").textContent=data.length;$("relConcluidos").textContent=data.filter(x=>x.status==="concluido").length;$("relCancelados").textContent=data.filter(x=>x.status==="cancelado").length;$("relFaltas").textContent=data.filter(x=>x.status==="nao_compareceu").length;
 let pg={};data.forEach(x=>{let n=pros.find(p=>p.id===x.profissional_id)?.nome||"Profissional";pg[n]??={q:0,v:0};pg[n].q++;pg[n].v+=Number(x.valor_pago||0)});$("relProfissionais").innerHTML=Object.keys(pg).length?Object.entries(pg).map(([n,v])=>`<div class="report-rank"><div><strong>${safe(n)}</strong><span>${v.q} atendimento(s)</span></div><strong>${money(v.v)}</strong></div>`).join(""):'<div class="empty-state">Sem dados.</div>';
 let sg={};links.forEach(x=>{let n=serv.find(s=>s.id===x.servico_id)?.nome||"Serviço";sg[n]=(sg[n]||0)+1});$("relServicos").innerHTML=Object.keys(sg).length?Object.entries(sg).sort((a,b)=>b[1]-a[1]).map(([n,q])=>`<div class="report-rank"><strong>${safe(n)}</strong><span>${q}</span></div>`).join(""):'<div class="empty-state">Sem serviços no período.</div>';
}
document.addEventListener("DOMContentLoaded",async()=>{defaults("relInicio","relFim");await load();$("relAplicar").onclick=load;$("exportRelatorio").onclick=()=>csv("lis-beauty-relatorio.csv",[["Indicador","Valor"],["Agendamentos",data.length],["Concluídos",data.filter(x=>x.status==="concluido").length],["Cancelados",data.filter(x=>x.status==="cancelado").length],["Não compareceu",data.filter(x=>x.status==="nao_compareceu").length],[],["Profissional","Atendimentos","Recebido"],...pros.map(p=>{let a=data.filter(x=>x.profissional_id===p.id);return[p.nome,a.length,a.reduce((t,x)=>t+Number(x.valor_pago||0),0).toFixed(2)]})])});
